# Generated by Django 5.2.7 on 2025-10-24 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('card_id', models.CharField(db_index=True, max_length=128)),
                ('rating', models.IntegerField()),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'card_id'], name='scheduler_r_user_id_4214c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('card_id', models.CharField(db_index=True, max_length=128)),
                ('next_review', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_interval_seconds', models.BigIntegerField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'card_id')},
            },
        ),
    ]
